version: '3.7'
services:
  php:
    build: ./docker/php
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    volumes: ['./symfony/:/var/www/symfony:cached']
  gatling:
    build: ./docker/gatling
    volumes: ['./gatling/results/:/opt/gatling/results','./gatling/simulations/:/opt/gatling/user-files/simulations']