version: '3.7'
services:
  gatling:
    build: ./docker/gatling
    volumes: ['./gatling/results/:/opt/gatling/results','./gatling/simulations/:/opt/gatling/user-files/simulations']
    networks:
      - default
networks:
  default:
    external:
      name: my-pre-existing-network